name: Daily Bitcoin Sentiment Update

on:
  schedule:
    - cron: '0 7 * * *'  # Run at midnight PST
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw pandas requests numpy bs4 plotly textblob

      - name: Run sentiment analysis
        run: python Bitcoin_FG_Index.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Daily sentiment update for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
