name: Daily Bitcoin Sentiment Update

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC every day
  workflow_dispatch:  # Allow manual triggering from GitHub UI

jobs:
  update-sentiment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw pandas requests numpy bs4 plotly textblob

      - name: Run sentiment analysis
        env:
          # Add your Reddit API credentials as secrets in your GitHub repository
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        run: |
          python Bitcoin_FG_Index.py
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add sentiment_scores.csv index_index.html line_index.html
          git commit -m "Daily sentiment update for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
